using Questify.Builder.Logic.Service.Properties;
using System.Collections.Generic;

namespace Questify.Builder.Logic.Service.HelperFunctions.Symbols
{
    public class SpecialSymbolGroup
    {
        public static readonly IEnumerable<SpecialSymbolGroup> Symbols = new[]
        {
            new SpecialSymbolGroup(Resources.LatinExtendedCharacters, new[]
            {
                new SpecialSymbol("&Agrave;", 192, "Latin capital letter A with grave"),
                new SpecialSymbol("&Aacute;", 193, "Latin capital letter A with acute"),
                new SpecialSymbol("&Acirc;", 194, "Latin capital letter A with circumflex"),
                new SpecialSymbol("&Atilde;", 195, "Latin capital letter A with tilde"),
                new SpecialSymbol("&Auml;", 196, "Latin capital letter A with diaeresis"),
                new SpecialSymbol("&Aring;", 197, "Latin capital letter A with ring above"),
                new SpecialSymbol("&AElig;", 198, "Latin capital letter AE"),
                new SpecialSymbol("&agrave;", 224, "Latin small letter a with grave"),
                new SpecialSymbol("&aacute;", 225, "Latin small letter a with acute"),
                new SpecialSymbol("&acirc;", 226, "Latin small letter a with circumflex"),
                new SpecialSymbol("&atilde;", 227, "Latin small letter a with tilde"),
                new SpecialSymbol("&auml;", 228, "Latin small letter a with diaeresis"),
                new SpecialSymbol("&aring;", 229, "Latin small letter a with ring above"),
                new SpecialSymbol("&aelig;", 230, "Latin small letter ae"),
                new SpecialSymbol("&Ograve;", 210, "Latin capital letter O with grave"),
                new SpecialSymbol("&oacute;", 211, "Latin capital letter O with acute"),
                new SpecialSymbol("&Ocirc;", 212, "Latin capital letter O with circumflex"),
                new SpecialSymbol("&Otilde;", 213, "Latin capital letter O with tilde"),
                new SpecialSymbol("&Ouml;", 214, "Latin capital letter O with diaeresis"),
                new SpecialSymbol("&ograve;", 242, "Latin small letter o with grave"),
                new SpecialSymbol("&oacute;", 243, "Latin small letter o with acute"),
                new SpecialSymbol("&ocirc;", 244, "Latin small letter o with circumflex"),
                new SpecialSymbol("&otilde;", 245, "Latin small letter o with tilde"),
                new SpecialSymbol("&ouml;", 246, "Latin small letter o with diaeresis"),
                new SpecialSymbol("&Egrave;", 200, "Latin capital letter E with grave"),
                new SpecialSymbol("&Eacute;", 201, "Latin capital letter E with acute"),
                new SpecialSymbol("&Ecirc;", 202, "Latin capital letter E with circumflex"),
                new SpecialSymbol("&Euml;", 203, "Latin capital letter E with diaeresis"),
                new SpecialSymbol("&egrave;", 232, "Latin small letter e with grave"),
                new SpecialSymbol("&eacute;", 233, "Latin small letter e with acute"),
                new SpecialSymbol("&ecirc;", 234, "Latin small letter e with circumflex"),
                new SpecialSymbol("&euml;", 235, "Latin small letter e with diaeresis"),
                new SpecialSymbol("&Igrave;", 204, "Latin capital letter I with grave"),
                new SpecialSymbol("&Iacute;", 205, "Latin capital letter I with acute"),
                new SpecialSymbol("&Icirc;", 206, "Latin capital letter I with circumflex"),
                new SpecialSymbol("&Iuml;", 207, "Latin capital letter I with diaeresis"),
                new SpecialSymbol("&igrave;", 236, "Latin small letter i with grave"),
                new SpecialSymbol("&iacute;", 237, "Latin small letter i with acute"),
                new SpecialSymbol("&icirc;", 238, "Latin small letter i with circumflex"),
                new SpecialSymbol("&iuml;", 239, "Latin small letter i with diaeresis"),
                new SpecialSymbol("&Ugrave;", 217, "Latin capital letter U with grave"),
                new SpecialSymbol("&Uacute;", 218, "Latin capital letter U with acute"),
                new SpecialSymbol("&Ucirc;", 219, "Latin capital letter U with circumflex"),
                new SpecialSymbol("&Uuml;", 220, "Latin capital letter U with diaeresis"),
                new SpecialSymbol("&ugrave;", 249, "Latin small letter u with grave"),
                new SpecialSymbol("&uacute;", 250, "Latin small letter u with acute"),
                new SpecialSymbol("&ucirc;", 251, "Latin small letter with circumflex"),
                new SpecialSymbol("&uuml;", 252, "Latin small letter u with diaeresis"),
                new SpecialSymbol("&Yacute;", 221, "Latin capital letter Y with acute"),
                new SpecialSymbol("&Yuml;", 376, "Latin capital letter Y with diaeresis"),
                new SpecialSymbol("&yacute;", 253, "Latin small letter y with acute"),
                new SpecialSymbol("&yuml;", 255, "Latin small letter y with diaeresis"),
                new SpecialSymbol("&Ccedil;", 199, "Latin capital letter C with cedilla"),
                new SpecialSymbol("&ccedil;", 231, "Latin small letter c with cedilla"),
                new SpecialSymbol("&Scaron;", 352, "Latin capital letter S with caron"),
                new SpecialSymbol("&scaron;", 353, "Latin small letter s with caron"),
                new SpecialSymbol("&ETH;", 208, "Latin capital letter Eth"),
                new SpecialSymbol("&eth;", 240, "Latin small letter eth"),
                new SpecialSymbol("&Ntilde;", 209, "Latin capital letter N with tilde"),
                new SpecialSymbol("&ntilde;", 241, "Latin small letter n with tilde"),
                new SpecialSymbol("&THORN;", 222, "Latin capital letter Thorn"),
                new SpecialSymbol("&thorn;", 254, "Latin small letter thorn"),
                new SpecialSymbol("&OELIG;", 338, "Latin capital ligature OE"),
                new SpecialSymbol("&oelig;", 339, "Latin small ligature oe"),
                new SpecialSymbol("&szlig;", 223, "Latin small letter sharp s")
            }),
            new SpecialSymbolGroup(Resources.GreekCharacters,  new[]
            {
                new SpecialSymbol("&#913;", 913, "capital Alpha"),
                new SpecialSymbol("&#914;", 914, "capital Beta"),
                new SpecialSymbol("&#915;", 915, "capital Gamma"),
                new SpecialSymbol("&#916;", 916, "capital Delta"),
                new SpecialSymbol("&#917;", 917, "capital Epsilon"),
                new SpecialSymbol("&#918;", 918, "capital Zeta"),
                new SpecialSymbol("&#919;", 919, "capital Eta"),
                new SpecialSymbol("&#920;", 920, "capital Theta"),
                new SpecialSymbol("&#921;", 921, "capital Iota"),
                new SpecialSymbol("&#922;", 922, "capital Kappa"),
                new SpecialSymbol("&#923;", 923, "capital Lambda"),
                new SpecialSymbol("&#924;", 924, "capital Mu"),
                new SpecialSymbol("&#925;", 925, "capital Nu"),
                new SpecialSymbol("&#926;", 926, "capital Xi"),
                new SpecialSymbol("&#927;", 927, "capital Omicron"),
                new SpecialSymbol("&#928;", 928, "capital Pi"),
                new SpecialSymbol("&#929;", 929, "capital Rho"),
                new SpecialSymbol("&#931;", 931, "capital Sigma"),
                new SpecialSymbol("&#932;", 932, "capital Tau"),
                new SpecialSymbol("&#933;", 933, "capital Upsilon"),
                new SpecialSymbol("&#934;", 934, "capital Phi"),
                new SpecialSymbol("&#935;", 935, "capital Chi"),
                new SpecialSymbol("&#936;", 936, "capital Psi"),
                new SpecialSymbol("&#937;", 937, "capital Omega"),
                new SpecialSymbol("&#938;", 938, "capital Iota with dialytika"),
                new SpecialSymbol("&#939;", 939, "capital Upsilon with dialytika"),
                new SpecialSymbol("&#940;", 940, "lower case alpha with tonos"),
                new SpecialSymbol("&#941;", 941, "lower case epsilon with tonos"),
                new SpecialSymbol("&#942;", 942, "lower case eta with tonos"),
                new SpecialSymbol("&#943;", 943, "lower case iota with tonos"),
                new SpecialSymbol("&#944;", 944, "lower case upsilon with dialytika and tonos"),
                new SpecialSymbol("&#945;", 945, "lower case alpha"),
                new SpecialSymbol("&#946;", 946, "lower case beta"),
                new SpecialSymbol("&#947;", 947, "lower case gamma"),
                new SpecialSymbol("&#948;", 948, "lower case delta"),
                new SpecialSymbol("&#949;", 949, "lower case epsilon"),
                new SpecialSymbol("&#950;", 950, "lower case zeta"),
                new SpecialSymbol("&#951;", 951, "lower case eta"),
                new SpecialSymbol("&#952;", 952, "lower case theta"),
                new SpecialSymbol("&#953;", 953, "lower case iota"),
                new SpecialSymbol("&#954;", 954, "lower case kappa"),
                new SpecialSymbol("&#955;", 955, "lower case lambda"),
                new SpecialSymbol("&#956;", 956, "lower case mu"),
                new SpecialSymbol("&#957;", 957, "lower case nu"),
                new SpecialSymbol("&#958;", 958, "lower case xi"),
                new SpecialSymbol("&#959;", 959, "lower case omicron"),
                new SpecialSymbol("&#960;", 960, "lower case pi"),
                new SpecialSymbol("&#961;", 961, "lower case rho"),
                new SpecialSymbol("&#962;", 962, "lower case sigma (terminal)"),
                new SpecialSymbol("&#963;", 963, "lower case sigma"),
                new SpecialSymbol("&#964;", 964, "lower case tau"),
                new SpecialSymbol("&#965;", 965, "lower case upsilon"),
                new SpecialSymbol("&#966;", 966, "lower case phi"),
                new SpecialSymbol("&#967;", 967, "lower case chi"),
                new SpecialSymbol("&#968;", 968, "lower case psi"),
                new SpecialSymbol("&#969;", 969, "lower case omega"),
                new SpecialSymbol("&#970;", 970, "lower case iota with dialytika"),
                new SpecialSymbol("&#971;", 971, "lower case upsilon with dialytika"),
                new SpecialSymbol("&#972;", 972, "lower case omicron with tonos"),
                new SpecialSymbol("&#973;", 973, "lower case upsilon with tonos"),
                new SpecialSymbol("&#974;", 974, "lower case omega with tonos")
            }),
            new SpecialSymbolGroup(Resources.Diacritics, new[]
            {
                new SpecialSymbol("&Ccaron;", 268, "Latin capital Letter C with caron"),
                new SpecialSymbol("&ccaron;", 269, "Latin small letter c with caron"),
                new SpecialSymbol("&Dcaron;", 270, "Latin capital Letter D with caron"),
                new SpecialSymbol("&dcaron;", 271, "Latin small letter d with caron"),
                new SpecialSymbol("&Ecaron;", 282, "Latin capital Letter E with caron"),
                new SpecialSymbol("&ecaron;", 283, "Latin small letter e with caron"),
                new SpecialSymbol("&Ncaron;", 327, "Latin capital Letter N with caron"),
                new SpecialSymbol("&ncaron;", 328, "Latin small letter n with caron"),
                new SpecialSymbol("&Rcaron;", 344, "Latin capital Letter R with caron"),
                new SpecialSymbol("&rcaron;", 345, "Latin small letter r with caron"),
                new SpecialSymbol("&Scaron;", 352, "Latin capital Letter S with caron"),
                new SpecialSymbol("&scaron;", 353, "Latin small letter s with caron"),
                new SpecialSymbol("&Tcaron;", 356, "Latin capital letter T with caron"),
                new SpecialSymbol("&tcaron;", 357, "Latin small letter t with caron"),
                new SpecialSymbol("&Uring;", 366, "Latin capital letter U with ring above"),
                new SpecialSymbol("&uring;", 367, "Latin small letter u with ring above"),
                new SpecialSymbol("&Zcaron;", 381, "Latin capital letter Z with caron"),
                new SpecialSymbol("&Zcaron;", 382, "Latin small letter z with caron"),
            }),
            new SpecialSymbolGroup(Resources.SpecialSymbols, new[]
            {
                new SpecialSymbol("&#8239", 8239, "narrow no-break space"),
                new SpecialSymbol("&#064;", 64, "At sign"),
                new SpecialSymbol("&quot;", 34, "quotation mark"),
                new SpecialSymbol("&iexcl;", 161, "inverted exclamation mark"),
                new SpecialSymbol("&cent;", 162, "cent sign"),
                new SpecialSymbol("&pound;", 163, "pound sign"),
                new SpecialSymbol("&curren;", 164, "currency sign"),
                new SpecialSymbol("&yen;", 165, "yen sign"),
                new SpecialSymbol("&brvbar;", 166, "broken bar"),
                new SpecialSymbol("&sect;", 167, "section sign"),
                new SpecialSymbol("&uml;", 168, "diaeresis"),
                new SpecialSymbol("&copy;", 169, "copyright sign"),
                new SpecialSymbol("&reg;", 174, "registered sign"),
                new SpecialSymbol("&ordf;", 170, "feminine ordinal indicator"),
                new SpecialSymbol("&not;", 172, "not sign"),
                new SpecialSymbol("&macr;", 175, "macron"),
                new SpecialSymbol("&deg;", 176, "degree sign"),
                new SpecialSymbol("&plusmn;", 177, "plus-minus sign"),
                new SpecialSymbol("&sup2;", 178, "superscript two"),
                new SpecialSymbol("&sup3;", 179, "superscript three"),
                new SpecialSymbol("&acute;", 180, "acute accent"),
                new SpecialSymbol("&micro;", 181, "micro sign"),
                new SpecialSymbol("&para;", 182, "pilcrow sign"),
                new SpecialSymbol("&middot;", 183, "middle dot"),
                new SpecialSymbol("&cedil;", 184, "cedilla"),
                new SpecialSymbol("&sup1;", 185, "superscript one"),
                new SpecialSymbol("&ordm;", 186, "masculine ordinal indicator"),
                new SpecialSymbol("&laquo;", 171, "left-pointing double angle quotation mark"),
                new SpecialSymbol("&raquo;", 187, "right-pointing double angle quotation mark"),
                new SpecialSymbol("&frac14;", 188, "vulgar fraction one quarter"),
                new SpecialSymbol("&frac12;", 189, "vulgar fraction one half"),
                new SpecialSymbol("&frac34;", 190, "vulgar fraction three quarters"),
                new SpecialSymbol("&iquest;", 191, "inverted question mark"),
                new SpecialSymbol("&times;", 215, "multiplication sign"),
                new SpecialSymbol("&divide;", 247, "division sign"),
                new SpecialSymbol("&Oslash;", 216, "Latin capital letter O with stroke"),
                new SpecialSymbol("&oslash;", 248, "Latin small letter o with stroke"),
                new SpecialSymbol("&fnof;", 402, "Latin small letter f with hook"),
                new SpecialSymbol("&circ;", 710, "modifier letter circumflex accent"),
                new SpecialSymbol("&tilde;", 732, "small tilde"),
                new SpecialSymbol("&ndash;", 8211, "en dash"),
                new SpecialSymbol("&mdash;", 8212, "em dash"),
                new SpecialSymbol("&lsquo;", 8216, "left single quotation mark"),
                new SpecialSymbol("&rsquo;", 8217, "right single quotation mark"),
                new SpecialSymbol("&sbquo;", 8218, "single low-9 quotation mark"),
                new SpecialSymbol("&ldquo;", 8220, "left double quotation mark"),
                new SpecialSymbol("&rdquo;", 8221, "right double quotation mark"),
                new SpecialSymbol("&bdquo;", 8222, "double low-9 quotation mark"),
                new SpecialSymbol("&dagger;", 8224, "dagger"),
                new SpecialSymbol("&Dagger;", 8225, "double dagger"),
                new SpecialSymbol("&bull;", 8226, "bullet"),
                new SpecialSymbol("&hellip;", 8230, "horizontal ellipsis"),
                new SpecialSymbol("&permil;", 8240, "per mille sign"),
                new SpecialSymbol("&lsaquo;", 8249, "single left-pointing angle quotation mark"),
                new SpecialSymbol("&rsaquo;", 8250, "single right-pointing angle quotation mark"),
                new SpecialSymbol("&euro;", 8364, "euro sign"),
                new SpecialSymbol("&trade;", 8482, "trade mark sign")
            })
        };

        private SpecialSymbolGroup(string name, IEnumerable<SpecialSymbol> symbols)
        {
            Name = name;
            SymbolList = symbols;
        }

        public string Name { get; private set; }
        public IEnumerable<SpecialSymbol> SymbolList { get; private set; }
    }
}