using System;

namespace Questify.Builder.Security.ActiveDirectory.DsObjectPicker
{

    [Flags]
    internal enum DSOP_SCOPE_TYPE_FLAGS : uint
    {
        DSOP_SCOPE_TYPE_TARGET_COMPUTER = 0x00000001,
        DSOP_SCOPE_TYPE_UPLEVEL_JOINED_DOMAIN = 0x00000002,
        DSOP_SCOPE_TYPE_DOWNLEVEL_JOINED_DOMAIN = 0x00000004,
        DSOP_SCOPE_TYPE_ENTERPRISE_DOMAIN = 0x00000008,
        DSOP_SCOPE_TYPE_GLOBAL_CATALOG = 0x00000010,
        DSOP_SCOPE_TYPE_EXTERNAL_UPLEVEL_DOMAIN = 0x00000020,
        DSOP_SCOPE_TYPE_EXTERNAL_DOWNLEVEL_DOMAIN = 0x00000040,
        DSOP_SCOPE_TYPE_WORKGROUP = 0x00000080,
        DSOP_SCOPE_TYPE_USER_ENTERED_UPLEVEL_SCOPE = 0x00000100,
        DSOP_SCOPE_TYPE_USER_ENTERED_DOWNLEVEL_SCOPE = 0x00000200
    }

    [Flags]
    internal enum DSOP_INIT_INFO_FLAGS : uint
    {
        DSOP_FLAG_MULTISELECT = 0x1,
        DSOP_FLAG_SKIP_TARGET_COMPUTER_DC_CHECK = 0x2
    }

    [Flags]
    internal enum DSOP_SCOPE_INIT_INFO_FLAGS : uint
    {
        DSOP_SCOPE_FLAG_STARTING_SCOPE = 0x00000001,
        DSOP_SCOPE_FLAG_WANT_PROVIDER_WINNT = 0x00000002,
        DSOP_SCOPE_FLAG_WANT_PROVIDER_LDAP = 0x00000004,
        DSOP_SCOPE_FLAG_WANT_PROVIDER_GC = 0x00000008,
        DSOP_SCOPE_FLAG_WANT_SID_PATH = 0x00000010,
        DSOP_SCOPE_FLAG_WANT_DOWNLEVEL_BUILTIN_PATH = 0x00000020,

        DSOP_SCOPE_FLAG_DEFAULT_FILTER_USERS = 0x00000040,
        DSOP_SCOPE_FLAG_DEFAULT_FILTER_GROUPS = 0x00000080,
        DSOP_SCOPE_FLAG_DEFAULT_FILTER_COMPUTERS = 0x00000100,
        DSOP_SCOPE_FLAG_DEFAULT_FILTER_CONTACTS = 0x00000200
    }

    [Flags]
    internal enum DSOP_FILTER_FLAGS_FLAGS : uint
    {
        DSOP_FILTER_INCLUDE_ADVANCED_VIEW = 0x00000001,
        DSOP_FILTER_USERS = 0x00000002,
        DSOP_FILTER_BUILTIN_GROUPS = 0x00000004,
        DSOP_FILTER_WELL_KNOWN_PRINCIPALS = 0x00000008,
        DSOP_FILTER_UNIVERSAL_GROUPS_DL = 0x00000010,
        DSOP_FILTER_UNIVERSAL_GROUPS_SE = 0x00000020,
        DSOP_FILTER_GLOBAL_GROUPS_DL = 0x00000040,
        DSOP_FILTER_GLOBAL_GROUPS_SE = 0x00000080,
        DSOP_FILTER_DOMAIN_LOCAL_GROUPS_DL = 0x00000100,
        DSOP_FILTER_DOMAIN_LOCAL_GROUPS_SE = 0x00000200,
        DSOP_FILTER_CONTACTS = 0x00000400,
        DSOP_FILTER_COMPUTERS = 0x00000800
    }

    [Flags]
    internal enum DSOP_DOWNLEVEL_FLAGS : uint
    {
        DSOP_DOWNLEVEL_FILTER_USERS = 0x1,
        DSOP_DOWNLEVEL_FILTER_LOCAL_GROUPS = 0x2,
        DSOP_DOWNLEVEL_FILTER_GLOBAL_GROUPS = 0x4,
        DSOP_DOWNLEVEL_FILTER_COMPUTERS = 0x8,
        DSOP_DOWNLEVEL_FILTER_WORLD = 0x10,
        DSOP_DOWNLEVEL_FILTER_AUTHENTICATED_USER = 0x20,
        DSOP_DOWNLEVEL_FILTER_ANONYMOUS = 0x40,
        DSOP_DOWNLEVEL_FILTER_BATCH = 0x80,
        DSOP_DOWNLEVEL_FILTER_CREATOR_OWNER = 0x100,
        DSOP_DOWNLEVEL_FILTER_CREATOR_GROUP = 0x200,
        DSOP_DOWNLEVEL_FILTER_DIALUP = 0x400,
        DSOP_DOWNLEVEL_FILTER_INTERACTIVE = 0x800,
        DSOP_DOWNLEVEL_FILTER_NETWORK = 0x1000,
        DSOP_DOWNLEVEL_FILTER_SERVICE = 0x2000,
        DSOP_DOWNLEVEL_FILTER_SYSTEM = 0x4000,
        DSOP_DOWNLEVEL_FILTER_EXCLUDE_BUILTIN_GROUPS = 0x8000,
        DSOP_DOWNLEVEL_FILTER_TERMINAL_SERVER = 0x10000,
        DSOP_DOWNLEVEL_FILTER_ALL_WELLKNOWN_SIDS = 0x20000,
        DSOP_DOWNLEVEL_FILTER_LOCAL_SERVICE = 0x40000,
        DSOP_DOWNLEVEL_FILTER_NETWORK_SERVICE = 0x80000,
        DSOP_DOWNLEVEL_FILTER_REMOTE_LOGON = 0x100000
    }

    public class CLIPBOARD_FORMAT
    {
        public const string CFSTR_DSOP_DS_SELECTION_LIST =
            "CFSTR_DSOP_DS_SELECTION_LIST";
    }

    public enum TYMED
    {
        TYMED_HGLOBAL = 1,
        TYMED_FILE = 2,
        TYMED_ISTREAM = 4,
        TYMED_ISTORAGE = 8,
        TYMED_GDI = 16,
        TYMED_MFPICT = 32,
        TYMED_ENHMF = 64,
        TYMED_NULL = 0
    }

    public enum DVASPECT
    {
        DVASPECT_CONTENT = 1,
        DVASPECT_THUMBNAIL = 2,
        DVASPECT_ICON = 4,
        DVASPECT_DOCPRINT = 8
    }

}
