--MERGE generated by 'sp_generate_merge' stored procedure, Version 0.93
--Originally by Vyas (http://vyaskn.tripod.com); adapted for SQL Server 2008/2012 by Daniel Nolan (http://danere.com)

SET NOCOUNT ON

SET IDENTITY_INSERT [dbo].[Role] ON

--Are roles present? If so, do nothing!
DECLARE @RoleCnt int
SELECT @RoleCnt = (select COUNT(*) from [dbo].[Role]  ) 
IF @RoleCnt = 0

BEGIN
	MERGE INTO [dbo].[Role] AS Target
		USING (VALUES
			 (1,'Application administrator','Application administrator',1,GETDATE(),1,GETDATE(),1)
			,(2,'Guest','Guest',1,GETDATE(),1,GETDATE(),1)
		) AS Source ([id],[name],[description],[isApplicationRole],[creationDate],[createdBy],[modifiedDate],[modifiedBy])
		ON (Target.[id] = Source.[id])
		WHEN MATCHED AND (
			NULLIF(Source.[name], Target.[name]) IS NOT NULL OR NULLIF(Target.[name], Source.[name]) IS NOT NULL OR 
			NULLIF(Source.[description], Target.[description]) IS NOT NULL OR NULLIF(Target.[description], Source.[description]) IS NOT NULL OR 
			NULLIF(Source.[isApplicationRole], Target.[isApplicationRole]) IS NOT NULL OR NULLIF(Target.[isApplicationRole], Source.[isApplicationRole]) IS NOT NULL OR 
			NULLIF(Source.[creationDate], Target.[creationDate]) IS NOT NULL OR NULLIF(Target.[creationDate], Source.[creationDate]) IS NOT NULL OR 
			NULLIF(Source.[createdBy], Target.[createdBy]) IS NOT NULL OR NULLIF(Target.[createdBy], Source.[createdBy]) IS NOT NULL OR 
			NULLIF(Source.[modifiedDate], Target.[modifiedDate]) IS NOT NULL OR NULLIF(Target.[modifiedDate], Source.[modifiedDate]) IS NOT NULL OR 
			NULLIF(Source.[modifiedBy], Target.[modifiedBy]) IS NOT NULL OR NULLIF(Target.[modifiedBy], Source.[modifiedBy]) IS NOT NULL) THEN
		UPDATE SET
			[name] = Source.[name], 
			[description] = Source.[description], 
			[isApplicationRole] = Source.[isApplicationRole], 
			[creationDate] = Source.[creationDate], 
			[createdBy] = Source.[createdBy], 
			[modifiedDate] = Source.[modifiedDate], 
			[modifiedBy] = Source.[modifiedBy]
		WHEN NOT MATCHED BY TARGET THEN
		 INSERT([id],[name],[description],[isApplicationRole],[creationDate],[createdBy],[modifiedDate],[modifiedBy])
		 VALUES(Source.[id],Source.[name],Source.[description],Source.[isApplicationRole],Source.[creationDate],Source.[createdBy],Source.[modifiedDate],Source.[modifiedBy])
		WHEN NOT MATCHED BY SOURCE THEN 
		 DELETE;
END

GO
DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [dbo].[Role]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[dbo].[Role] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END
GO

SET IDENTITY_INSERT [dbo].[Role] OFF
GO
SET NOCOUNT OFF
GO