--MERGE generated by 'sp_generate_merge' stored procedure, Version 0.93
--Originally by Vyas (http://vyaskn.tripod.com); adapted for SQL Server 2008/2012 by Daniel Nolan (http://danere.com)

SET NOCOUNT ON

SET IDENTITY_INSERT [dbo].[Bank] ON

--Are banks present? If so, do nothing!
DECLARE @BnkCnt int
SELECT @BnkCnt = (select COUNT(*) from [dbo].[Bank]  ) 
IF @BnkCnt = 0
BEGIN

MERGE INTO [dbo].[Bank] AS Target
USING (VALUES
  (1,NULL,'QuestifyBank',NULL,GETDATE(),1,GETDATE(),1)
) AS Source ([id],[parentBankId],[name],[type],[creationDate],[createdBy],[modifiedDate],[modifiedBy])
ON (Target.[id] = Source.[id])
WHEN MATCHED AND (
	NULLIF(Source.[parentBankId], Target.[parentBankId]) IS NOT NULL OR NULLIF(Target.[parentBankId], Source.[parentBankId]) IS NOT NULL OR 
	NULLIF(Source.[name], Target.[name]) IS NOT NULL OR NULLIF(Target.[name], Source.[name]) IS NOT NULL OR 
	NULLIF(Source.[type], Target.[type]) IS NOT NULL OR NULLIF(Target.[type], Source.[type]) IS NOT NULL OR 
	NULLIF(Source.[creationDate], Target.[creationDate]) IS NOT NULL OR NULLIF(Target.[creationDate], Source.[creationDate]) IS NOT NULL OR 
	NULLIF(Source.[createdBy], Target.[createdBy]) IS NOT NULL OR NULLIF(Target.[createdBy], Source.[createdBy]) IS NOT NULL OR 
	NULLIF(Source.[modifiedDate], Target.[modifiedDate]) IS NOT NULL OR NULLIF(Target.[modifiedDate], Source.[modifiedDate]) IS NOT NULL OR 
	NULLIF(Source.[modifiedBy], Target.[modifiedBy]) IS NOT NULL OR NULLIF(Target.[modifiedBy], Source.[modifiedBy]) IS NOT NULL) THEN
 UPDATE SET
 [parentBankId] = Source.[parentBankId], 
[name] = Source.[name], 
[type] = Source.[type], 
[creationDate] = Source.[creationDate], 
[createdBy] = Source.[createdBy], 
[modifiedDate] = Source.[modifiedDate], 
[modifiedBy] = Source.[modifiedBy]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([id],[parentBankId],[name],[type],[creationDate],[createdBy],[modifiedDate],[modifiedBy])
 VALUES(Source.[id],Source.[parentBankId],Source.[name],Source.[type],Source.[creationDate],Source.[createdBy],Source.[modifiedDate],Source.[modifiedBy]);

END

GO
DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [dbo].[Bank]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[dbo].[Bank] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END
GO

SET IDENTITY_INSERT [dbo].[Bank] OFF
GO
SET NOCOUNT OFF
GO