--MERGE generated by 'sp_generate_merge' stored procedure, Version 0.93
--Originally by Vyas (http://vyaskn.tripod.com); adapted for SQL Server 2008/2012 by Daniel Nolan (http://danere.com)

SET NOCOUNT ON

--Are concept types present? If so, do nothing!
DECLARE @CTCnt int
SELECT @CTCnt = (select COUNT(*) from [dbo].[ConceptType]  ) 
IF @CTCnt = 0
BEGIN

MERGE INTO [dbo].[ConceptType] AS Target
USING (VALUES
  (1,'Part',3)
 ,(2,'Attribute',2)
 ,(3,'PartAttribute',2)
 ,(4,'ResponseStrategy',2)
 ,(5,'Domain',2)
 ,(6,'SubDomain',2)
 ,(7,'PartPartAttribute',2)
 ,(8,'Bottleneck',2)
) AS Source ([conceptTypeId],[name],[applicableToMask])
ON (Target.[conceptTypeId] = Source.[conceptTypeId])
WHEN MATCHED AND (
	NULLIF(Source.[name], Target.[name]) IS NOT NULL OR NULLIF(Target.[name], Source.[name]) IS NOT NULL OR 
	NULLIF(Source.[applicableToMask], Target.[applicableToMask]) IS NOT NULL OR NULLIF(Target.[applicableToMask], Source.[applicableToMask]) IS NOT NULL) THEN
 UPDATE SET
 [name] = Source.[name], 
[applicableToMask] = Source.[applicableToMask]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([conceptTypeId],[name],[applicableToMask])
 VALUES(Source.[conceptTypeId],Source.[name],Source.[applicableToMask])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE;

END

GO
DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [dbo].[ConceptType]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[dbo].[ConceptType] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END
GO

SET NOCOUNT OFF
GO