Imports System
Imports SD.LLBLGen.Pro.ORMSupportClasses



Namespace Questify.Builder.Model.ContentModel.HelperClasses
    Friend NotInheritable Class FieldInfoProviderSingleton
        Private Shared ReadOnly _providerInstance As IFieldInfoProvider = New FieldInfoProviderCore()

        Private Sub New()
        End Sub

        Shared Sub New()
        End Sub

        Public Shared Function GetInstance() As IFieldInfoProvider
            Return _providerInstance
        End Function
    End Class

    Friend Class FieldInfoProviderCore
        Inherits FieldInfoProviderBase
        Friend Sub New()
            Init()
        End Sub

        Private Sub Init()
            MyBase.InitClass()
            InitActionEntityInfos()
            InitAspectResourceEntityInfos()
            InitAssessmentTestResourceEntityInfos()
            InitBankEntityInfos()
            InitChildConceptStructurePartCustomBankPropertyEntityInfos()
            InitChildTreeStructurePartCustomBankPropertyEntityInfos()
            InitConceptStructureCustomBankPropertyEntityInfos()
            InitConceptStructureCustomBankPropertySelectedPartEntityInfos()
            InitConceptStructureCustomBankPropertyValueEntityInfos()
            InitConceptStructurePartCustomBankPropertyEntityInfos()
            InitConceptTypeEntityInfos()
            InitControlTemplateResourceEntityInfos()
            InitCustomBankPropertyEntityInfos()
            InitCustomBankPropertyValueEntityInfos()
            InitDataSourceResourceEntityInfos()
            InitDependentResourceEntityInfos()
            InitFreeValueCustomBankPropertyEntityInfos()
            InitFreeValueCustomBankPropertyValueEntityInfos()
            InitGenericResourceEntityInfos()
            InitHiddenResourceEntityInfos()
            InitItemLayoutTemplateResourceEntityInfos()
            InitItemResourceEntityInfos()
            InitListCustomBankPropertyEntityInfos()
            InitListCustomBankPropertySelectedValueEntityInfos()
            InitListCustomBankPropertyValueEntityInfos()
            InitListValueCustomBankPropertyEntityInfos()
            InitPackageResourceEntityInfos()
            InitPermissionEntityInfos()
            InitPermissionTargetEntityInfos()
            InitResourceEntityInfos()
            InitResourceDataEntityInfos()
            InitResourceHistoryEntityInfos()
            InitRichTextValueCustomBankPropertyEntityInfos()
            InitRichTextValueCustomBankPropertyValueEntityInfos()
            InitRoleEntityInfos()
            InitRolePermissionEntityInfos()
            InitStateEntityInfos()
            InitStateActionEntityInfos()
            InitTestPackageResourceEntityInfos()
            InitTreeStructureCustomBankPropertyEntityInfos()
            InitTreeStructureCustomBankPropertySelectedPartEntityInfos()
            InitTreeStructureCustomBankPropertyValueEntityInfos()
            InitTreeStructurePartCustomBankPropertyEntityInfos()
            InitUserEntityInfos()
            InitUserApplicationRoleEntityInfos()
            InitUserBankRoleEntityInfos()

            MyBase.ConstructElementFieldStructures(InheritanceInfoProviderSingleton.GetInstance())
        End Sub

        Private Sub InitActionEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(ActionFieldIndex), "ActionEntity")
            Me.AddElementFieldInfo("ActionEntity", "ActionId", GetType(System.Int32), True, False, True, False, CInt(ActionFieldIndex.ActionId), 0, 0, 10)
            Me.AddElementFieldInfo("ActionEntity", "Name", GetType(System.String), False, False, False, False, CInt(ActionFieldIndex.Name), 50, 0, 0)
            Me.AddElementFieldInfo("ActionEntity", "Title", GetType(System.String), False, False, False, True, CInt(ActionFieldIndex.Title), 50, 0, 0)
        End Sub
        Private Sub InitAspectResourceEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(AspectResourceFieldIndex), "AspectResourceEntity")
            Me.AddElementFieldInfo("AspectResourceEntity", "ResourceId", GetType(System.Guid), True, False, False, False, CInt(AspectResourceFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("AspectResourceEntity", "RawScore", GetType(System.Int32), False, False, False, False, CInt(AspectResourceFieldIndex.RawScore), 0, 0, 10)
        End Sub
        Private Sub InitAssessmentTestResourceEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(AssessmentTestResourceFieldIndex), "AssessmentTestResourceEntity")
            Me.AddElementFieldInfo("AssessmentTestResourceEntity", "ResourceId", GetType(System.Guid), True, False, False, False, CInt(AssessmentTestResourceFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("AssessmentTestResourceEntity", "IsTemplate", GetType(System.Boolean), False, False, False, False, CInt(AssessmentTestResourceFieldIndex.IsTemplate), 0, 0, 0)
        End Sub
        Private Sub InitBankEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(BankFieldIndex), "BankEntity")
            Me.AddElementFieldInfo("BankEntity", "Id", GetType(System.Int32), True, False, True, False, CInt(BankFieldIndex.Id), 0, 0, 10)
            Me.AddElementFieldInfo("BankEntity", "ParentBankId", GetType(Nullable(Of System.Int32)), False, True, False, True, CInt(BankFieldIndex.ParentBankId), 0, 0, 10)
            Me.AddElementFieldInfo("BankEntity", "Name", GetType(System.String), False, False, False, False, CInt(BankFieldIndex.Name), 50, 0, 0)
            Me.AddElementFieldInfo("BankEntity", "Type", GetType(System.String), False, False, False, True, CInt(BankFieldIndex.Type), 50, 0, 0)
            Me.AddElementFieldInfo("BankEntity", "CreationDate", GetType(System.DateTime), False, False, False, False, CInt(BankFieldIndex.CreationDate), 0, 0, 0)
            Me.AddElementFieldInfo("BankEntity", "CreatedBy", GetType(System.Int32), False, True, False, False, CInt(BankFieldIndex.CreatedBy), 0, 0, 10)
            Me.AddElementFieldInfo("BankEntity", "ModifiedDate", GetType(System.DateTime), False, False, False, False, CInt(BankFieldIndex.ModifiedDate), 0, 0, 0)
            Me.AddElementFieldInfo("BankEntity", "ModifiedBy", GetType(System.Int32), False, True, False, False, CInt(BankFieldIndex.ModifiedBy), 0, 0, 10)
        End Sub
        Private Sub InitChildConceptStructurePartCustomBankPropertyEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(ChildConceptStructurePartCustomBankPropertyFieldIndex), "ChildConceptStructurePartCustomBankPropertyEntity")
            Me.AddElementFieldInfo("ChildConceptStructurePartCustomBankPropertyEntity", "Id", GetType(System.Guid), True, False, False, False, CInt(ChildConceptStructurePartCustomBankPropertyFieldIndex.Id), 0, 0, 0)
            Me.AddElementFieldInfo("ChildConceptStructurePartCustomBankPropertyEntity", "ConceptStructurePartCustomBankPropertyId", GetType(System.Guid), True, True, False, False, CInt(ChildConceptStructurePartCustomBankPropertyFieldIndex.ConceptStructurePartCustomBankPropertyId), 0, 0, 0)
            Me.AddElementFieldInfo("ChildConceptStructurePartCustomBankPropertyEntity", "ChildConceptStructurePartCustomBankPropertyId", GetType(System.Guid), True, True, False, False, CInt(ChildConceptStructurePartCustomBankPropertyFieldIndex.ChildConceptStructurePartCustomBankPropertyId), 0, 0, 0)
            Me.AddElementFieldInfo("ChildConceptStructurePartCustomBankPropertyEntity", "VisualOrder", GetType(System.Int32), False, False, False, False, CInt(ChildConceptStructurePartCustomBankPropertyFieldIndex.VisualOrder), 0, 0, 10)
        End Sub
        Private Sub InitChildTreeStructurePartCustomBankPropertyEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(ChildTreeStructurePartCustomBankPropertyFieldIndex), "ChildTreeStructurePartCustomBankPropertyEntity")
            Me.AddElementFieldInfo("ChildTreeStructurePartCustomBankPropertyEntity", "Id", GetType(System.Guid), True, False, False, False, CInt(ChildTreeStructurePartCustomBankPropertyFieldIndex.Id), 0, 0, 0)
            Me.AddElementFieldInfo("ChildTreeStructurePartCustomBankPropertyEntity", "ChildTreeStructurePartCustomBankPropertyId", GetType(System.Guid), True, False, False, False, CInt(ChildTreeStructurePartCustomBankPropertyFieldIndex.ChildTreeStructurePartCustomBankPropertyId), 0, 0, 0)
            Me.AddElementFieldInfo("ChildTreeStructurePartCustomBankPropertyEntity", "TreeStructurePartCustomBankPropertyId", GetType(System.Guid), True, True, False, False, CInt(ChildTreeStructurePartCustomBankPropertyFieldIndex.TreeStructurePartCustomBankPropertyId), 0, 0, 0)
            Me.AddElementFieldInfo("ChildTreeStructurePartCustomBankPropertyEntity", "VisualOrder", GetType(System.Int32), False, False, False, False, CInt(ChildTreeStructurePartCustomBankPropertyFieldIndex.VisualOrder), 0, 0, 10)
        End Sub
        Private Sub InitConceptStructureCustomBankPropertyEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(ConceptStructureCustomBankPropertyFieldIndex), "ConceptStructureCustomBankPropertyEntity")
            Me.AddElementFieldInfo("ConceptStructureCustomBankPropertyEntity", "CustomBankPropertyId", GetType(System.Guid), True, False, False, False, CInt(ConceptStructureCustomBankPropertyFieldIndex.CustomBankPropertyId), 0, 0, 0)
        End Sub
        Private Sub InitConceptStructureCustomBankPropertySelectedPartEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(ConceptStructureCustomBankPropertySelectedPartFieldIndex), "ConceptStructureCustomBankPropertySelectedPartEntity")
            Me.AddElementFieldInfo("ConceptStructureCustomBankPropertySelectedPartEntity", "ConceptStructurePartId", GetType(System.Guid), True, True, False, False, CInt(ConceptStructureCustomBankPropertySelectedPartFieldIndex.ConceptStructurePartId), 0, 0, 0)
            Me.AddElementFieldInfo("ConceptStructureCustomBankPropertySelectedPartEntity", "ResourceId", GetType(System.Guid), True, True, False, False, CInt(ConceptStructureCustomBankPropertySelectedPartFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("ConceptStructureCustomBankPropertySelectedPartEntity", "CustomBankPropertyId", GetType(System.Guid), True, True, False, False, CInt(ConceptStructureCustomBankPropertySelectedPartFieldIndex.CustomBankPropertyId), 0, 0, 0)
        End Sub
        Private Sub InitConceptStructureCustomBankPropertyValueEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(ConceptStructureCustomBankPropertyValueFieldIndex), "ConceptStructureCustomBankPropertyValueEntity")
            Me.AddElementFieldInfo("ConceptStructureCustomBankPropertyValueEntity", "ResourceId", GetType(System.Guid), True, True, False, False, CInt(ConceptStructureCustomBankPropertyValueFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("ConceptStructureCustomBankPropertyValueEntity", "CustomBankPropertyId", GetType(System.Guid), True, True, False, False, CInt(ConceptStructureCustomBankPropertyValueFieldIndex.CustomBankPropertyId), 0, 0, 0)
        End Sub
        Private Sub InitConceptStructurePartCustomBankPropertyEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(ConceptStructurePartCustomBankPropertyFieldIndex), "ConceptStructurePartCustomBankPropertyEntity")
            Me.AddElementFieldInfo("ConceptStructurePartCustomBankPropertyEntity", "ConceptStructurePartCustomBankPropertyId", GetType(System.Guid), True, False, False, False, CInt(ConceptStructurePartCustomBankPropertyFieldIndex.ConceptStructurePartCustomBankPropertyId), 0, 0, 0)
            Me.AddElementFieldInfo("ConceptStructurePartCustomBankPropertyEntity", "CustomBankPropertyId", GetType(System.Guid), False, True, False, False, CInt(ConceptStructurePartCustomBankPropertyFieldIndex.CustomBankPropertyId), 0, 0, 0)
            Me.AddElementFieldInfo("ConceptStructurePartCustomBankPropertyEntity", "Name", GetType(System.String), False, False, False, False, CInt(ConceptStructurePartCustomBankPropertyFieldIndex.Name), 50, 0, 0)
            Me.AddElementFieldInfo("ConceptStructurePartCustomBankPropertyEntity", "Title", GetType(System.String), False, False, False, True, CInt(ConceptStructurePartCustomBankPropertyFieldIndex.Title), 255, 0, 0)
            Me.AddElementFieldInfo("ConceptStructurePartCustomBankPropertyEntity", "Code", GetType(System.Guid), False, False, False, False, CInt(ConceptStructurePartCustomBankPropertyFieldIndex.Code), 0, 0, 0)
            Me.AddElementFieldInfo("ConceptStructurePartCustomBankPropertyEntity", "ConceptTypeId", GetType(System.Int32), False, True, False, False, CInt(ConceptStructurePartCustomBankPropertyFieldIndex.ConceptTypeId), 0, 0, 10)
        End Sub
        Private Sub InitConceptTypeEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(ConceptTypeFieldIndex), "ConceptTypeEntity")
            Me.AddElementFieldInfo("ConceptTypeEntity", "ConceptTypeId", GetType(System.Int32), True, False, False, False, CInt(ConceptTypeFieldIndex.ConceptTypeId), 0, 0, 10)
            Me.AddElementFieldInfo("ConceptTypeEntity", "Name", GetType(System.String), False, False, False, False, CInt(ConceptTypeFieldIndex.Name), 255, 0, 0)
            Me.AddElementFieldInfo("ConceptTypeEntity", "ApplicableToMask", GetType(System.Int32), False, False, False, False, CInt(ConceptTypeFieldIndex.ApplicableToMask), 0, 0, 10)
        End Sub
        Private Sub InitControlTemplateResourceEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(ControlTemplateResourceFieldIndex), "ControlTemplateResourceEntity")
            Me.AddElementFieldInfo("ControlTemplateResourceEntity", "ResourceId", GetType(System.Guid), True, False, False, False, CInt(ControlTemplateResourceFieldIndex.ResourceId), 0, 0, 0)
        End Sub
        Private Sub InitCustomBankPropertyEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(CustomBankPropertyFieldIndex), "CustomBankPropertyEntity")
            Me.AddElementFieldInfo("CustomBankPropertyEntity", "CustomBankPropertyId", GetType(System.Guid), True, False, False, False, CInt(CustomBankPropertyFieldIndex.CustomBankPropertyId), 0, 0, 0)
            Me.AddElementFieldInfo("CustomBankPropertyEntity", "BankId", GetType(System.Int32), False, True, False, False, CInt(CustomBankPropertyFieldIndex.BankId), 0, 0, 10)
            Me.AddElementFieldInfo("CustomBankPropertyEntity", "ApplicableToMask", GetType(Nullable(Of System.Int32)), False, False, False, True, CInt(CustomBankPropertyFieldIndex.ApplicableToMask), 0, 0, 10)
            Me.AddElementFieldInfo("CustomBankPropertyEntity", "Publishable", GetType(System.Boolean), False, False, False, False, CInt(CustomBankPropertyFieldIndex.Publishable), 0, 0, 0)
            Me.AddElementFieldInfo("CustomBankPropertyEntity", "Scorable", GetType(System.Boolean), False, False, False, False, CInt(CustomBankPropertyFieldIndex.Scorable), 0, 0, 0)
            Me.AddElementFieldInfo("CustomBankPropertyEntity", "Name", GetType(System.String), False, False, False, False, CInt(CustomBankPropertyFieldIndex.Name), 50, 0, 0)
            Me.AddElementFieldInfo("CustomBankPropertyEntity", "Title", GetType(System.String), False, False, False, True, CInt(CustomBankPropertyFieldIndex.Title), 255, 0, 0)
            Me.AddElementFieldInfo("CustomBankPropertyEntity", "Description", GetType(System.String), False, False, False, True, CInt(CustomBankPropertyFieldIndex.Description), 2147483647, 0, 0)
            Me.AddElementFieldInfo("CustomBankPropertyEntity", "CreationDate", GetType(System.DateTime), False, False, False, False, CInt(CustomBankPropertyFieldIndex.CreationDate), 0, 0, 0)
            Me.AddElementFieldInfo("CustomBankPropertyEntity", "CreatedBy", GetType(System.Int32), False, True, False, False, CInt(CustomBankPropertyFieldIndex.CreatedBy), 0, 0, 10)
            Me.AddElementFieldInfo("CustomBankPropertyEntity", "ModifiedDate", GetType(System.DateTime), False, False, False, False, CInt(CustomBankPropertyFieldIndex.ModifiedDate), 0, 0, 0)
            Me.AddElementFieldInfo("CustomBankPropertyEntity", "ModifiedBy", GetType(System.Int32), False, True, False, False, CInt(CustomBankPropertyFieldIndex.ModifiedBy), 0, 0, 10)
            Me.AddElementFieldInfo("CustomBankPropertyEntity", "Code", GetType(System.Guid), False, False, False, False, CInt(CustomBankPropertyFieldIndex.Code), 0, 0, 0)
            Me.AddElementFieldInfo("CustomBankPropertyEntity", "StateId", GetType(Nullable(Of System.Int32)), False, True, False, True, CInt(CustomBankPropertyFieldIndex.StateId), 0, 0, 10)
            Me.AddElementFieldInfo("CustomBankPropertyEntity", "Version", GetType(System.String), False, False, False, False, CInt(CustomBankPropertyFieldIndex.Version), 20, 0, 0)
        End Sub
        Private Sub InitCustomBankPropertyValueEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(CustomBankPropertyValueFieldIndex), "CustomBankPropertyValueEntity")
            Me.AddElementFieldInfo("CustomBankPropertyValueEntity", "ResourceId", GetType(System.Guid), True, True, False, False, CInt(CustomBankPropertyValueFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("CustomBankPropertyValueEntity", "CustomBankPropertyId", GetType(System.Guid), True, True, False, False, CInt(CustomBankPropertyValueFieldIndex.CustomBankPropertyId), 0, 0, 0)
            Me.AddElementFieldInfo("CustomBankPropertyValueEntity", "DisplayValue", GetType(System.String), False, False, False, True, CInt(CustomBankPropertyValueFieldIndex.DisplayValue), 255, 0, 0)
        End Sub
        Private Sub InitDataSourceResourceEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(DataSourceResourceFieldIndex), "DataSourceResourceEntity")
            Me.AddElementFieldInfo("DataSourceResourceEntity", "ResourceId", GetType(System.Guid), True, False, False, False, CInt(DataSourceResourceFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("DataSourceResourceEntity", "DataSourceType", GetType(System.String), False, False, False, False, CInt(DataSourceResourceFieldIndex.DataSourceType), 255, 0, 0)
            Me.AddElementFieldInfo("DataSourceResourceEntity", "IsTemplate", GetType(System.Boolean), False, False, False, False, CInt(DataSourceResourceFieldIndex.IsTemplate), 0, 0, 0)
        End Sub
        Private Sub InitDependentResourceEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(DependentResourceFieldIndex), "DependentResourceEntity")
            Me.AddElementFieldInfo("DependentResourceEntity", "ResourceId", GetType(System.Guid), True, True, False, False, CInt(DependentResourceFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("DependentResourceEntity", "DependentResourceId", GetType(System.Guid), True, True, False, False, CInt(DependentResourceFieldIndex.DependentResourceId), 0, 0, 0)
        End Sub
        Private Sub InitFreeValueCustomBankPropertyEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(FreeValueCustomBankPropertyFieldIndex), "FreeValueCustomBankPropertyEntity")
            Me.AddElementFieldInfo("FreeValueCustomBankPropertyEntity", "CustomBankPropertyId", GetType(System.Guid), True, False, False, False, CInt(FreeValueCustomBankPropertyFieldIndex.CustomBankPropertyId), 0, 0, 0)
        End Sub
        Private Sub InitFreeValueCustomBankPropertyValueEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(FreeValueCustomBankPropertyValueFieldIndex), "FreeValueCustomBankPropertyValueEntity")
            Me.AddElementFieldInfo("FreeValueCustomBankPropertyValueEntity", "ResourceId", GetType(System.Guid), True, True, False, False, CInt(FreeValueCustomBankPropertyValueFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("FreeValueCustomBankPropertyValueEntity", "CustomBankPropertyId", GetType(System.Guid), True, True, False, False, CInt(FreeValueCustomBankPropertyValueFieldIndex.CustomBankPropertyId), 0, 0, 0)
            Me.AddElementFieldInfo("FreeValueCustomBankPropertyValueEntity", "Value", GetType(System.String), False, False, False, True, CInt(FreeValueCustomBankPropertyValueFieldIndex.Value), 255, 0, 0)
            Me.AddElementFieldInfo("FreeValueCustomBankPropertyValueEntity", "FreeValueCustomBankPropertyValueId", GetType(System.Int32), False, False, True, False, CInt(FreeValueCustomBankPropertyValueFieldIndex.FreeValueCustomBankPropertyValueId), 0, 0, 10)
        End Sub
        Private Sub InitGenericResourceEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(GenericResourceFieldIndex), "GenericResourceEntity")
            Me.AddElementFieldInfo("GenericResourceEntity", "ResourceId", GetType(System.Guid), True, False, False, False, CInt(GenericResourceFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("GenericResourceEntity", "MediaType", GetType(System.String), False, False, False, False, CInt(GenericResourceFieldIndex.MediaType), 255, 0, 0)
            Me.AddElementFieldInfo("GenericResourceEntity", "Size", GetType(System.Int32), False, False, False, False, CInt(GenericResourceFieldIndex.Size), 0, 0, 10)
            Me.AddElementFieldInfo("GenericResourceEntity", "Dimensions", GetType(System.String), False, False, False, True, CInt(GenericResourceFieldIndex.Dimensions), 50, 0, 0)
            Me.AddElementFieldInfo("GenericResourceEntity", "IsTemplate", GetType(System.Boolean), False, False, False, False, CInt(GenericResourceFieldIndex.IsTemplate), 0, 0, 0)
        End Sub
        Private Sub InitHiddenResourceEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(HiddenResourceFieldIndex), "HiddenResourceEntity")
            Me.AddElementFieldInfo("HiddenResourceEntity", "ResourceId", GetType(System.Guid), True, True, False, False, CInt(HiddenResourceFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("HiddenResourceEntity", "BankId", GetType(System.Int32), True, False, False, False, CInt(HiddenResourceFieldIndex.BankId), 0, 0, 10)
        End Sub
        Private Sub InitItemLayoutTemplateResourceEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(ItemLayoutTemplateResourceFieldIndex), "ItemLayoutTemplateResourceEntity")
            Me.AddElementFieldInfo("ItemLayoutTemplateResourceEntity", "ResourceId", GetType(System.Guid), True, False, False, False, CInt(ItemLayoutTemplateResourceFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("ItemLayoutTemplateResourceEntity", "ItemType", GetType(System.String), False, False, False, True, CInt(ItemLayoutTemplateResourceFieldIndex.ItemType), 50, 0, 0)
        End Sub
        Private Sub InitItemResourceEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(ItemResourceFieldIndex), "ItemResourceEntity")
            Me.AddElementFieldInfo("ItemResourceEntity", "ResourceId", GetType(System.Guid), True, False, False, False, CInt(ItemResourceFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("ItemResourceEntity", "IsSystemItem", GetType(System.Boolean), False, False, False, False, CInt(ItemResourceFieldIndex.IsSystemItem), 0, 0, 0)
            Me.AddElementFieldInfo("ItemResourceEntity", "AlternativesCount", GetType(Nullable(Of System.Int32)), False, False, False, True, CInt(ItemResourceFieldIndex.AlternativesCount), 0, 0, 10)
            Me.AddElementFieldInfo("ItemResourceEntity", "KeyValues", GetType(System.String), False, False, False, True, CInt(ItemResourceFieldIndex.KeyValues), 500, 0, 0)
            Me.AddElementFieldInfo("ItemResourceEntity", "ResponseCount", GetType(Nullable(Of System.Int32)), False, False, False, True, CInt(ItemResourceFieldIndex.ResponseCount), 0, 0, 10)
            Me.AddElementFieldInfo("ItemResourceEntity", "RawScore", GetType(Nullable(Of System.Int32)), False, False, False, True, CInt(ItemResourceFieldIndex.RawScore), 0, 0, 10)
            Me.AddElementFieldInfo("ItemResourceEntity", "TesterSchemaVersion", GetType(Nullable(Of System.Int32)), False, False, False, True, CInt(ItemResourceFieldIndex.TesterSchemaVersion), 0, 0, 10)
            Me.AddElementFieldInfo("ItemResourceEntity", "Iltname", GetType(System.String), False, False, False, True, CInt(ItemResourceFieldIndex.Iltname), 255, 0, 0)
            Me.AddElementFieldInfo("ItemResourceEntity", "Iltversion", GetType(Nullable(Of System.Int32)), False, False, False, True, CInt(ItemResourceFieldIndex.Iltversion), 0, 0, 10)
            Me.AddElementFieldInfo("ItemResourceEntity", "MaxScore", GetType(Nullable(Of System.Decimal)), False, False, False, True, CInt(ItemResourceFieldIndex.MaxScore), 0, 2, 9)
            Me.AddElementFieldInfo("ItemResourceEntity", "ItemAutoId", GetType(System.Int32), False, False, True, False, CInt(ItemResourceFieldIndex.ItemAutoId), 0, 0, 10)
            Me.AddElementFieldInfo("ItemResourceEntity", "ItemId", GetType(System.String), False, False, False, True, CInt(ItemResourceFieldIndex.ItemId), 6, 0, 0)
        End Sub
        Private Sub InitListCustomBankPropertyEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(ListCustomBankPropertyFieldIndex), "ListCustomBankPropertyEntity")
            Me.AddElementFieldInfo("ListCustomBankPropertyEntity", "CustomBankPropertyId", GetType(System.Guid), True, False, False, False, CInt(ListCustomBankPropertyFieldIndex.CustomBankPropertyId), 0, 0, 0)
            Me.AddElementFieldInfo("ListCustomBankPropertyEntity", "MultipleSelect", GetType(System.Boolean), False, False, False, False, CInt(ListCustomBankPropertyFieldIndex.MultipleSelect), 0, 0, 0)
        End Sub
        Private Sub InitListCustomBankPropertySelectedValueEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(ListCustomBankPropertySelectedValueFieldIndex), "ListCustomBankPropertySelectedValueEntity")
            Me.AddElementFieldInfo("ListCustomBankPropertySelectedValueEntity", "ResourceId", GetType(System.Guid), True, True, False, False, CInt(ListCustomBankPropertySelectedValueFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("ListCustomBankPropertySelectedValueEntity", "CustomBankPropertyId", GetType(System.Guid), True, True, False, False, CInt(ListCustomBankPropertySelectedValueFieldIndex.CustomBankPropertyId), 0, 0, 0)
            Me.AddElementFieldInfo("ListCustomBankPropertySelectedValueEntity", "ListValueBankCustomPropertyId", GetType(System.Guid), True, True, False, False, CInt(ListCustomBankPropertySelectedValueFieldIndex.ListValueBankCustomPropertyId), 0, 0, 0)
        End Sub
        Private Sub InitListCustomBankPropertyValueEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(ListCustomBankPropertyValueFieldIndex), "ListCustomBankPropertyValueEntity")
            Me.AddElementFieldInfo("ListCustomBankPropertyValueEntity", "ResourceId", GetType(System.Guid), True, True, False, False, CInt(ListCustomBankPropertyValueFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("ListCustomBankPropertyValueEntity", "CustomBankPropertyId", GetType(System.Guid), True, True, False, False, CInt(ListCustomBankPropertyValueFieldIndex.CustomBankPropertyId), 0, 0, 0)
        End Sub
        Private Sub InitListValueCustomBankPropertyEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(ListValueCustomBankPropertyFieldIndex), "ListValueCustomBankPropertyEntity")
            Me.AddElementFieldInfo("ListValueCustomBankPropertyEntity", "ListValueBankCustomPropertyId", GetType(System.Guid), True, False, False, False, CInt(ListValueCustomBankPropertyFieldIndex.ListValueBankCustomPropertyId), 0, 0, 0)
            Me.AddElementFieldInfo("ListValueCustomBankPropertyEntity", "CustomBankPropertyId", GetType(System.Guid), False, True, False, False, CInt(ListValueCustomBankPropertyFieldIndex.CustomBankPropertyId), 0, 0, 0)
            Me.AddElementFieldInfo("ListValueCustomBankPropertyEntity", "Name", GetType(System.String), False, False, False, False, CInt(ListValueCustomBankPropertyFieldIndex.Name), 50, 0, 0)
            Me.AddElementFieldInfo("ListValueCustomBankPropertyEntity", "Title", GetType(System.String), False, False, False, True, CInt(ListValueCustomBankPropertyFieldIndex.Title), 255, 0, 0)
            Me.AddElementFieldInfo("ListValueCustomBankPropertyEntity", "Code", GetType(System.Guid), False, False, False, False, CInt(ListValueCustomBankPropertyFieldIndex.Code), 0, 0, 0)
        End Sub
        Private Sub InitPackageResourceEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(PackageResourceFieldIndex), "PackageResourceEntity")
            Me.AddElementFieldInfo("PackageResourceEntity", "ResourceId", GetType(System.Guid), True, False, False, False, CInt(PackageResourceFieldIndex.ResourceId), 0, 0, 0)
        End Sub
        Private Sub InitPermissionEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(PermissionFieldIndex), "PermissionEntity")
            Me.AddElementFieldInfo("PermissionEntity", "Id", GetType(System.Int32), True, False, False, False, CInt(PermissionFieldIndex.Id), 0, 0, 10)
            Me.AddElementFieldInfo("PermissionEntity", "Name", GetType(System.String), False, False, False, False, CInt(PermissionFieldIndex.Name), 20, 0, 0)
            Me.AddElementFieldInfo("PermissionEntity", "Description", GetType(System.String), False, False, False, True, CInt(PermissionFieldIndex.Description), 50, 0, 0)
            Me.AddElementFieldInfo("PermissionEntity", "WhenOwnerCondition", GetType(System.Boolean), False, False, False, False, CInt(PermissionFieldIndex.WhenOwnerCondition), 0, 0, 0)
            Me.AddElementFieldInfo("PermissionEntity", "CreationDate", GetType(System.DateTime), False, False, False, False, CInt(PermissionFieldIndex.CreationDate), 0, 0, 0)
            Me.AddElementFieldInfo("PermissionEntity", "CreatedBy", GetType(System.Int32), False, False, False, False, CInt(PermissionFieldIndex.CreatedBy), 0, 0, 10)
            Me.AddElementFieldInfo("PermissionEntity", "ModifiedDate", GetType(System.DateTime), False, False, False, False, CInt(PermissionFieldIndex.ModifiedDate), 0, 0, 0)
            Me.AddElementFieldInfo("PermissionEntity", "ModifiedBy", GetType(System.Int32), False, False, False, False, CInt(PermissionFieldIndex.ModifiedBy), 0, 0, 10)
        End Sub
        Private Sub InitPermissionTargetEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(PermissionTargetFieldIndex), "PermissionTargetEntity")
            Me.AddElementFieldInfo("PermissionTargetEntity", "Id", GetType(System.Int32), True, False, False, False, CInt(PermissionTargetFieldIndex.Id), 0, 0, 10)
            Me.AddElementFieldInfo("PermissionTargetEntity", "Name", GetType(System.String), False, False, False, False, CInt(PermissionTargetFieldIndex.Name), 50, 0, 0)
            Me.AddElementFieldInfo("PermissionTargetEntity", "TargettedNamedTask", GetType(System.String), False, False, False, True, CInt(PermissionTargetFieldIndex.TargettedNamedTask), 50, 0, 0)
            Me.AddElementFieldInfo("PermissionTargetEntity", "IsApplicationTarget", GetType(System.Boolean), False, False, False, False, CInt(PermissionTargetFieldIndex.IsApplicationTarget), 0, 0, 0)
            Me.AddElementFieldInfo("PermissionTargetEntity", "CreationDate", GetType(System.DateTime), False, False, False, False, CInt(PermissionTargetFieldIndex.CreationDate), 0, 0, 0)
            Me.AddElementFieldInfo("PermissionTargetEntity", "CreatedBy", GetType(System.Int32), False, False, False, False, CInt(PermissionTargetFieldIndex.CreatedBy), 0, 0, 10)
            Me.AddElementFieldInfo("PermissionTargetEntity", "ModifiedDate", GetType(System.DateTime), False, False, False, False, CInt(PermissionTargetFieldIndex.ModifiedDate), 0, 0, 0)
            Me.AddElementFieldInfo("PermissionTargetEntity", "ModifiedBy", GetType(System.Int32), False, False, False, False, CInt(PermissionTargetFieldIndex.ModifiedBy), 0, 0, 10)
        End Sub
        Private Sub InitResourceEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(ResourceFieldIndex), "ResourceEntity")
            Me.AddElementFieldInfo("ResourceEntity", "ResourceId", GetType(System.Guid), True, False, False, False, CInt(ResourceFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("ResourceEntity", "Version", GetType(System.String), False, False, False, False, CInt(ResourceFieldIndex.Version), 20, 0, 0)
            Me.AddElementFieldInfo("ResourceEntity", "BankId", GetType(System.Int32), False, True, False, False, CInt(ResourceFieldIndex.BankId), 0, 0, 10)
            Me.AddElementFieldInfo("ResourceEntity", "Name", GetType(System.String), False, False, False, False, CInt(ResourceFieldIndex.Name), 255, 0, 0)
            Me.AddElementFieldInfo("ResourceEntity", "Title", GetType(System.String), False, False, False, True, CInt(ResourceFieldIndex.Title), 255, 0, 0)
            Me.AddElementFieldInfo("ResourceEntity", "Description", GetType(System.String), False, False, False, True, CInt(ResourceFieldIndex.Description), 2147483647, 0, 0)
            Me.AddElementFieldInfo("ResourceEntity", "StateId", GetType(Nullable(Of System.Int32)), False, True, False, True, CInt(ResourceFieldIndex.StateId), 0, 0, 10)
            Me.AddElementFieldInfo("ResourceEntity", "CreationDate", GetType(System.DateTime), False, False, False, False, CInt(ResourceFieldIndex.CreationDate), 0, 0, 0)
            Me.AddElementFieldInfo("ResourceEntity", "CreatedBy", GetType(System.Int32), False, True, False, False, CInt(ResourceFieldIndex.CreatedBy), 0, 0, 10)
            Me.AddElementFieldInfo("ResourceEntity", "ModifiedDate", GetType(System.DateTime), False, False, False, False, CInt(ResourceFieldIndex.ModifiedDate), 0, 0, 0)
            Me.AddElementFieldInfo("ResourceEntity", "ModifiedBy", GetType(System.Int32), False, True, False, False, CInt(ResourceFieldIndex.ModifiedBy), 0, 0, 10)
            Me.AddElementFieldInfo("ResourceEntity", "OriginalVersion", GetType(System.String), False, False, False, True, CInt(ResourceFieldIndex.OriginalVersion), 20, 0, 0)
            Me.AddElementFieldInfo("ResourceEntity", "OriginalName", GetType(System.String), False, False, False, True, CInt(ResourceFieldIndex.OriginalName), 255, 0, 0)
        End Sub
        Private Sub InitResourceDataEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(ResourceDataFieldIndex), "ResourceDataEntity")
            Me.AddElementFieldInfo("ResourceDataEntity", "ResourceId", GetType(System.Guid), True, True, False, False, CInt(ResourceDataFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("ResourceDataEntity", "BinData", GetType(System.Byte()), False, False, False, True, CInt(ResourceDataFieldIndex.BinData), 2147483647, 0, 0)
            Me.AddElementFieldInfo("ResourceDataEntity", "Url", GetType(System.String), False, False, False, True, CInt(ResourceDataFieldIndex.Url), 500, 0, 0)
            Me.AddElementFieldInfo("ResourceDataEntity", "FileExtension", GetType(System.String), False, False, False, True, CInt(ResourceDataFieldIndex.FileExtension), 8, 0, 0)
            Me.AddElementFieldInfo("ResourceDataEntity", "Ident", GetType(System.Int64), False, False, True, False, CInt(ResourceDataFieldIndex.Ident), 0, 0, 19)
        End Sub
        Private Sub InitResourceHistoryEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(ResourceHistoryFieldIndex), "ResourceHistoryEntity")
            Me.AddElementFieldInfo("ResourceHistoryEntity", "Id", GetType(System.Int32), True, False, True, False, CInt(ResourceHistoryFieldIndex.Id), 0, 0, 10)
            Me.AddElementFieldInfo("ResourceHistoryEntity", "ResourceId", GetType(System.Guid), False, True, False, False, CInt(ResourceHistoryFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("ResourceHistoryEntity", "MajorVersion", GetType(System.Int16), False, False, False, False, CInt(ResourceHistoryFieldIndex.MajorVersion), 0, 0, 5)
            Me.AddElementFieldInfo("ResourceHistoryEntity", "MinorVersion", GetType(System.Int16), False, False, False, False, CInt(ResourceHistoryFieldIndex.MinorVersion), 0, 0, 5)
            Me.AddElementFieldInfo("ResourceHistoryEntity", "ModifiedBy", GetType(System.String), False, False, False, False, CInt(ResourceHistoryFieldIndex.ModifiedBy), 255, 0, 0)
            Me.AddElementFieldInfo("ResourceHistoryEntity", "ModifiedDate", GetType(System.DateTime), False, False, False, False, CInt(ResourceHistoryFieldIndex.ModifiedDate), 0, 0, 0)
            Me.AddElementFieldInfo("ResourceHistoryEntity", "Label", GetType(System.String), False, False, False, True, CInt(ResourceHistoryFieldIndex.Label), 4000, 0, 0)
            Me.AddElementFieldInfo("ResourceHistoryEntity", "BinData", GetType(System.Byte()), False, False, False, True, CInt(ResourceHistoryFieldIndex.BinData), 2147483647, 0, 0)
            Me.AddElementFieldInfo("ResourceHistoryEntity", "MetaData", GetType(System.Byte()), False, False, False, True, CInt(ResourceHistoryFieldIndex.MetaData), 2147483647, 0, 0)
        End Sub
        Private Sub InitRichTextValueCustomBankPropertyEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(RichTextValueCustomBankPropertyFieldIndex), "RichTextValueCustomBankPropertyEntity")
            Me.AddElementFieldInfo("RichTextValueCustomBankPropertyEntity", "CustomBankPropertyId", GetType(System.Guid), True, False, False, False, CInt(RichTextValueCustomBankPropertyFieldIndex.CustomBankPropertyId), 0, 0, 0)
        End Sub
        Private Sub InitRichTextValueCustomBankPropertyValueEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(RichTextValueCustomBankPropertyValueFieldIndex), "RichTextValueCustomBankPropertyValueEntity")
            Me.AddElementFieldInfo("RichTextValueCustomBankPropertyValueEntity", "ResourceId", GetType(System.Guid), True, True, False, False, CInt(RichTextValueCustomBankPropertyValueFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("RichTextValueCustomBankPropertyValueEntity", "CustomBankPropertyId", GetType(System.Guid), True, True, False, False, CInt(RichTextValueCustomBankPropertyValueFieldIndex.CustomBankPropertyId), 0, 0, 0)
            Me.AddElementFieldInfo("RichTextValueCustomBankPropertyValueEntity", "Value", GetType(System.String), False, False, False, True, CInt(RichTextValueCustomBankPropertyValueFieldIndex.Value), 2147483647, 0, 0)
            Me.AddElementFieldInfo("RichTextValueCustomBankPropertyValueEntity", "RichTextValueCustomBankPropertyValueId", GetType(System.Int32), False, False, True, False, CInt(RichTextValueCustomBankPropertyValueFieldIndex.RichTextValueCustomBankPropertyValueId), 0, 0, 10)
        End Sub
        Private Sub InitRoleEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(RoleFieldIndex), "RoleEntity")
            Me.AddElementFieldInfo("RoleEntity", "Id", GetType(System.Int32), True, False, True, False, CInt(RoleFieldIndex.Id), 0, 0, 10)
            Me.AddElementFieldInfo("RoleEntity", "Name", GetType(System.String), False, False, False, False, CInt(RoleFieldIndex.Name), 50, 0, 0)
            Me.AddElementFieldInfo("RoleEntity", "Description", GetType(System.String), False, False, False, True, CInt(RoleFieldIndex.Description), 50, 0, 0)
            Me.AddElementFieldInfo("RoleEntity", "IsApplicationRole", GetType(Nullable(Of System.Boolean)), False, False, False, True, CInt(RoleFieldIndex.IsApplicationRole), 0, 0, 0)
            Me.AddElementFieldInfo("RoleEntity", "CreationDate", GetType(System.DateTime), False, False, False, False, CInt(RoleFieldIndex.CreationDate), 0, 0, 0)
            Me.AddElementFieldInfo("RoleEntity", "CreatedBy", GetType(System.Int32), False, True, False, False, CInt(RoleFieldIndex.CreatedBy), 0, 0, 10)
            Me.AddElementFieldInfo("RoleEntity", "ModifiedDate", GetType(System.DateTime), False, False, False, False, CInt(RoleFieldIndex.ModifiedDate), 0, 0, 0)
            Me.AddElementFieldInfo("RoleEntity", "ModifiedBy", GetType(System.Int32), False, True, False, False, CInt(RoleFieldIndex.ModifiedBy), 0, 0, 10)
        End Sub
        Private Sub InitRolePermissionEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(RolePermissionFieldIndex), "RolePermissionEntity")
            Me.AddElementFieldInfo("RolePermissionEntity", "RoleId", GetType(System.Int32), True, True, False, False, CInt(RolePermissionFieldIndex.RoleId), 0, 0, 10)
            Me.AddElementFieldInfo("RolePermissionEntity", "PermissionTargetId", GetType(System.Int32), True, True, False, False, CInt(RolePermissionFieldIndex.PermissionTargetId), 0, 0, 10)
            Me.AddElementFieldInfo("RolePermissionEntity", "PermissionId", GetType(System.Int32), True, True, False, False, CInt(RolePermissionFieldIndex.PermissionId), 0, 0, 10)
            Me.AddElementFieldInfo("RolePermissionEntity", "CreationDate", GetType(System.DateTime), False, False, False, False, CInt(RolePermissionFieldIndex.CreationDate), 0, 0, 0)
            Me.AddElementFieldInfo("RolePermissionEntity", "CreatedBy", GetType(System.Int32), False, False, False, False, CInt(RolePermissionFieldIndex.CreatedBy), 0, 0, 10)
            Me.AddElementFieldInfo("RolePermissionEntity", "ModifiedDate", GetType(System.DateTime), False, False, False, False, CInt(RolePermissionFieldIndex.ModifiedDate), 0, 0, 0)
            Me.AddElementFieldInfo("RolePermissionEntity", "ModifiedBy", GetType(System.Int32), False, False, False, False, CInt(RolePermissionFieldIndex.ModifiedBy), 0, 0, 10)
        End Sub
        Private Sub InitStateEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(StateFieldIndex), "StateEntity")
            Me.AddElementFieldInfo("StateEntity", "StateId", GetType(System.Int32), True, False, True, False, CInt(StateFieldIndex.StateId), 0, 0, 10)
            Me.AddElementFieldInfo("StateEntity", "Name", GetType(System.String), False, False, False, False, CInt(StateFieldIndex.Name), 50, 0, 0)
            Me.AddElementFieldInfo("StateEntity", "Title", GetType(System.String), False, False, False, True, CInt(StateFieldIndex.Title), 50, 0, 0)
            Me.AddElementFieldInfo("StateEntity", "Description", GetType(System.String), False, False, False, True, CInt(StateFieldIndex.Description), 4000, 0, 0)
        End Sub
        Private Sub InitStateActionEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(StateActionFieldIndex), "StateActionEntity")
            Me.AddElementFieldInfo("StateActionEntity", "Target", GetType(System.String), True, False, False, False, CInt(StateActionFieldIndex.Target), 50, 0, 0)
            Me.AddElementFieldInfo("StateActionEntity", "StateId", GetType(System.Int32), True, True, False, False, CInt(StateActionFieldIndex.StateId), 0, 0, 10)
            Me.AddElementFieldInfo("StateActionEntity", "ActionId", GetType(System.Int32), True, True, False, False, CInt(StateActionFieldIndex.ActionId), 0, 0, 10)
        End Sub
        Private Sub InitTestPackageResourceEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(TestPackageResourceFieldIndex), "TestPackageResourceEntity")
            Me.AddElementFieldInfo("TestPackageResourceEntity", "ResourceId", GetType(System.Guid), True, False, False, False, CInt(TestPackageResourceFieldIndex.ResourceId), 0, 0, 0)
        End Sub
        Private Sub InitTreeStructureCustomBankPropertyEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(TreeStructureCustomBankPropertyFieldIndex), "TreeStructureCustomBankPropertyEntity")
            Me.AddElementFieldInfo("TreeStructureCustomBankPropertyEntity", "CustomBankPropertyId", GetType(System.Guid), True, False, False, False, CInt(TreeStructureCustomBankPropertyFieldIndex.CustomBankPropertyId), 0, 0, 0)
        End Sub
        Private Sub InitTreeStructureCustomBankPropertySelectedPartEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(TreeStructureCustomBankPropertySelectedPartFieldIndex), "TreeStructureCustomBankPropertySelectedPartEntity")
            Me.AddElementFieldInfo("TreeStructureCustomBankPropertySelectedPartEntity", "TreeStructurePartId", GetType(System.Guid), True, True, False, False, CInt(TreeStructureCustomBankPropertySelectedPartFieldIndex.TreeStructurePartId), 0, 0, 0)
            Me.AddElementFieldInfo("TreeStructureCustomBankPropertySelectedPartEntity", "ResourceId", GetType(System.Guid), True, True, False, False, CInt(TreeStructureCustomBankPropertySelectedPartFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("TreeStructureCustomBankPropertySelectedPartEntity", "CustomBankPropertyId", GetType(System.Guid), True, True, False, False, CInt(TreeStructureCustomBankPropertySelectedPartFieldIndex.CustomBankPropertyId), 0, 0, 0)
        End Sub
        Private Sub InitTreeStructureCustomBankPropertyValueEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(TreeStructureCustomBankPropertyValueFieldIndex), "TreeStructureCustomBankPropertyValueEntity")
            Me.AddElementFieldInfo("TreeStructureCustomBankPropertyValueEntity", "ResourceId", GetType(System.Guid), True, True, False, False, CInt(TreeStructureCustomBankPropertyValueFieldIndex.ResourceId), 0, 0, 0)
            Me.AddElementFieldInfo("TreeStructureCustomBankPropertyValueEntity", "CustomBankPropertyId", GetType(System.Guid), True, True, False, False, CInt(TreeStructureCustomBankPropertyValueFieldIndex.CustomBankPropertyId), 0, 0, 0)
        End Sub
        Private Sub InitTreeStructurePartCustomBankPropertyEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(TreeStructurePartCustomBankPropertyFieldIndex), "TreeStructurePartCustomBankPropertyEntity")
            Me.AddElementFieldInfo("TreeStructurePartCustomBankPropertyEntity", "TreeStructurePartCustomBankPropertyId", GetType(System.Guid), True, False, False, False, CInt(TreeStructurePartCustomBankPropertyFieldIndex.TreeStructurePartCustomBankPropertyId), 0, 0, 0)
            Me.AddElementFieldInfo("TreeStructurePartCustomBankPropertyEntity", "CustomBankPropertyId", GetType(System.Guid), False, True, False, False, CInt(TreeStructurePartCustomBankPropertyFieldIndex.CustomBankPropertyId), 0, 0, 0)
            Me.AddElementFieldInfo("TreeStructurePartCustomBankPropertyEntity", "Name", GetType(System.String), False, False, False, False, CInt(TreeStructurePartCustomBankPropertyFieldIndex.Name), 50, 0, 0)
            Me.AddElementFieldInfo("TreeStructurePartCustomBankPropertyEntity", "Title", GetType(System.String), False, False, False, True, CInt(TreeStructurePartCustomBankPropertyFieldIndex.Title), 255, 0, 0)
            Me.AddElementFieldInfo("TreeStructurePartCustomBankPropertyEntity", "Code", GetType(System.Guid), False, False, False, False, CInt(TreeStructurePartCustomBankPropertyFieldIndex.Code), 0, 0, 0)
        End Sub
        Private Sub InitUserEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(UserFieldIndex), "UserEntity")
            Me.AddElementFieldInfo("UserEntity", "Id", GetType(System.Int32), True, False, True, False, CInt(UserFieldIndex.Id), 0, 0, 10)
            Me.AddElementFieldInfo("UserEntity", "UserName", GetType(System.String), False, False, False, False, CInt(UserFieldIndex.UserName), 50, 0, 0)
            Me.AddElementFieldInfo("UserEntity", "Password", GetType(System.String), False, False, False, False, CInt(UserFieldIndex.Password), 2147483647, 0, 0)
            Me.AddElementFieldInfo("UserEntity", "FullName", GetType(System.String), False, False, False, False, CInt(UserFieldIndex.FullName), 50, 0, 0)
            Me.AddElementFieldInfo("UserEntity", "Active", GetType(System.Boolean), False, False, False, False, CInt(UserFieldIndex.Active), 0, 0, 0)
            Me.AddElementFieldInfo("UserEntity", "CreationDate", GetType(System.DateTime), False, False, False, False, CInt(UserFieldIndex.CreationDate), 0, 0, 0)
            Me.AddElementFieldInfo("UserEntity", "CreatedBy", GetType(System.Int32), False, True, False, False, CInt(UserFieldIndex.CreatedBy), 0, 0, 10)
            Me.AddElementFieldInfo("UserEntity", "ModifiedDate", GetType(System.DateTime), False, False, False, False, CInt(UserFieldIndex.ModifiedDate), 0, 0, 0)
            Me.AddElementFieldInfo("UserEntity", "ModifiedBy", GetType(System.Int32), False, True, False, False, CInt(UserFieldIndex.ModifiedBy), 0, 0, 10)
            Me.AddElementFieldInfo("UserEntity", "AuthenticationType", GetType(System.String), False, False, False, False, CInt(UserFieldIndex.AuthenticationType), 50, 0, 0)
            Me.AddElementFieldInfo("UserEntity", "UserSettings", GetType(System.String), False, False, False, False, CInt(UserFieldIndex.UserSettings), 2147483647, 0, 0)
            Me.AddElementFieldInfo("UserEntity", "ChangePassword", GetType(System.Boolean), False, False, False, False, CInt(UserFieldIndex.ChangePassword), 0, 0, 0)
            Me.AddElementFieldInfo("UserEntity", "AllowedFeatures", GetType(System.String), False, False, False, True, CInt(UserFieldIndex.AllowedFeatures), 2000, 0, 0)
        End Sub
        Private Sub InitUserApplicationRoleEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(UserApplicationRoleFieldIndex), "UserApplicationRoleEntity")
            Me.AddElementFieldInfo("UserApplicationRoleEntity", "UserId", GetType(System.Int32), True, True, False, False, CInt(UserApplicationRoleFieldIndex.UserId), 0, 0, 10)
            Me.AddElementFieldInfo("UserApplicationRoleEntity", "ApplicationRoleId", GetType(System.Int32), True, True, False, False, CInt(UserApplicationRoleFieldIndex.ApplicationRoleId), 0, 0, 10)
            Me.AddElementFieldInfo("UserApplicationRoleEntity", "CreationDate", GetType(System.DateTime), False, False, False, False, CInt(UserApplicationRoleFieldIndex.CreationDate), 0, 0, 0)
            Me.AddElementFieldInfo("UserApplicationRoleEntity", "CreatedBy", GetType(System.Int32), False, False, False, False, CInt(UserApplicationRoleFieldIndex.CreatedBy), 0, 0, 10)
            Me.AddElementFieldInfo("UserApplicationRoleEntity", "ModifiedDate", GetType(System.DateTime), False, False, False, False, CInt(UserApplicationRoleFieldIndex.ModifiedDate), 0, 0, 0)
            Me.AddElementFieldInfo("UserApplicationRoleEntity", "ModifiedBy", GetType(System.Int32), False, False, False, False, CInt(UserApplicationRoleFieldIndex.ModifiedBy), 0, 0, 10)
        End Sub
        Private Sub InitUserBankRoleEntityInfos()
            Me.AddFieldIndexEnumForElementName(GetType(UserBankRoleFieldIndex), "UserBankRoleEntity")
            Me.AddElementFieldInfo("UserBankRoleEntity", "UserId", GetType(System.Int32), True, True, False, False, CInt(UserBankRoleFieldIndex.UserId), 0, 0, 10)
            Me.AddElementFieldInfo("UserBankRoleEntity", "BankId", GetType(System.Int32), True, True, False, False, CInt(UserBankRoleFieldIndex.BankId), 0, 0, 10)
            Me.AddElementFieldInfo("UserBankRoleEntity", "BankRoleId", GetType(System.Int32), True, True, False, False, CInt(UserBankRoleFieldIndex.BankRoleId), 0, 0, 10)
            Me.AddElementFieldInfo("UserBankRoleEntity", "CreationDate", GetType(System.DateTime), False, False, False, False, CInt(UserBankRoleFieldIndex.CreationDate), 0, 0, 0)
            Me.AddElementFieldInfo("UserBankRoleEntity", "CreatedBy", GetType(System.Int32), False, False, False, False, CInt(UserBankRoleFieldIndex.CreatedBy), 0, 0, 10)
            Me.AddElementFieldInfo("UserBankRoleEntity", "ModifiedDate", GetType(System.DateTime), False, False, False, False, CInt(UserBankRoleFieldIndex.ModifiedDate), 0, 0, 0)
            Me.AddElementFieldInfo("UserBankRoleEntity", "ModifiedBy", GetType(System.Int32), False, False, False, False, CInt(UserBankRoleFieldIndex.ModifiedBy), 0, 0, 10)
        End Sub

    End Class
End Namespace







